#pragma config(Sensor, in2,    Claw,           sensorPotentiometer)
#pragma config(Sensor, dgtl2,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  liftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           RB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Lifts,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           BLA,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LA1,           tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           RA,            tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           LF,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LB,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//WANT -127&127 TURNS
//TWO UPPER ARM MOTOR NEED TO BE REVERSED;RA1=C LA1=D CLAW MOTOR UNSURE...
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
 // bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/
/*void drive(int inches, int power)
{
	SensorValue[rightEncoder] = 0; // reset encoders

	int ticks = inches/(4*PI)*360;                // 4 diameter

	while( abs(SensorValue(rightEncoder)) < ticks*0.7)//  when 70% of the ticks
	{
		motor[RF]=motor[RB]=motor[LF]=motor[LB]=power;
	}
	while( abs(SensorValue(rightEncoder)) < ticks)// when encoder is less thanb the ticks
	{
		motor[RF]=motor[RB]=motor[LF]=motor[LB]=power/2; // run all the run drive 1/2 of the speed

	}

	motor[RF] = motor[RB] = motor[LF] = motor[LB]=0; // come to a stop
}
*/
task autonomous()
{
	//These are for testsing
// go stright for 4 seconds
//turn left for 1.3 seconds
//Arm up for 1.3 sec, arm down for 1 sec, during the time lift comes out and goes back. everything stops
		motor[port3] = 127;
		motor[port2] = 127;
		motor[port8] = 127;
		motor[port9] = 127;
		wait1Msec(4000);


/*
		motor[port2] = 127;
		motor [port3] = 127;
		motor[port8] = 0;
		motor [port9] = 0;
		wait1Msec(1300);

		motor[RA]=motor[RA1]=motor[LA]=motor[LA1]=120;
	wait1Msec(1300);
	motor[RA]=motor[RA1]=motor[LA]=motor[LA1]=-120;
	motor[Lifts]=100;
	wait1Msec(1000);
		motor[Lifts]=-100;
	wait1Msec(1000);



		motor[port2]=motor[port3]=motor[port8]= motor[port9]=	motor[RA]=motor[RA1]=motor[LA]=motor[LA1]=0;

		/*These are for offical competition, use it after testing
		// go forward 48 inches
	drive(48,127);

	// pick up mobile goal
	motor[Lifts]=127;
	wait1Msec(1300); // pick up the mobile goal in highspeed, for 1.3 sec
	motor[Lifts]=-127;

	wait1Msec(1300);// return to orginal place in highspeed

	drive(50,-127);// go backwards 50 inches
	------//put the goal into 10 pt zone
 		motor[RF] = 127;
		motor [RB] = 127;
		motor[LB] = 0;
		motor [LF] = 0;
		wait1Msec(2000);// turn left for 2 sec
	motor[Lifts]=127;
	wait1Msec(1300);
	motor[Lifts]=-127;

	motor[LF] = 127;
		motor [LB] = 127;
		motor[RB] = 0;
		motor [RF] = 0;
		wait1Msec(2000);// turn left for 2 sec// at this time, robot should be in a stright motion
	// go forward 51 inches
	drive(51,127);

	//EVERYTHING STOPS
	motor[port1]=motor[port2]= motor[port3]=motor[port4]=motor[port5]=motor[port6]=motor[port7]=motor[port8]=motor[port9]=motor[port10]=0;
}
*/

  //AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
// Chanel 4 = updown &Channel 2= leftright
  while (true)
  {
  motor[LF]= motor[LB] = vexRT[Ch2]+ vexRT[Ch4] ; //
	motor[RF]= motor[RB] = vexRT[Ch4]-vexRT[Ch2]; //

	//------------------------------------------------------------------------------------------- 6 control the lifts

	if (vexRT[Btn6U]==1)
	{
	motor[Lifts]=120; // Lifts speed is determined by 6U going full speed
	}
	else if (vexRT[Btn6D]==1)
	{
	motor[Lifts]=-127;// LL,RL speed is determined by 6D going reverse full speed,
	}
	else
	{
	motor[Lifts]=0; // if nothing then 0
	}
  //------------------------------------------------------------- 8 control the arms
	if (vexRT[Btn8U]==1)
		{
		motor[RA]=motor[LA1]=120;
		motor[BLA]=-120; // LA,RA speed is determined by 8U going full speed
		}
		else if (vexRT[Btn8D]==1)
		{
		 	motor[RA]=motor[LA1]=-120;
		motor[BLA]=120;
	}
	if (vexRT[Btn8D]== 0 && vexRT[Btn8U]==0)
	{
	motor[BLA]= motor[RA]=motor[LA1]=20;// against gravity
}

  //--------------------------------------------------------------------------------------- 7 control claws
	if (vexRT[Btn7U]==1)
	{
	if (SensorValue[in2]< 2000) // if the sensor is less than 2500, then go
	{
		motor[claw]=107; //The claw speed is determined by 7U, going 107 as speed
	}
	else
	{
	motor[claw]=0;
 }
}
  if (vexRT[Btn7D]==1)
	{
	if (SensorValue[in2]> 600) // if the sensor is larger than 500, the minimum value
	{
		motor[claw]=-107; //The clasw speed is determined by 7D, going -107 BACK
	}
}

 if (vexRT[Btn7D]== 0 && vexRT[Btn7U]==0)
	{
	motor[claw]=0;
 }
    //UserControlCodePlaceholderForTesting();
  }
}
